[package]
name = "lpass-blob"
version = "0.1.0"
edition = "2021"

[dependencies]
base64 = "0.20.0"
hex = "0.4.3"
regex = "1.7.0"
serde = { version = "1.0.152", features = ["derive"] }
serde-xml-rs = "0.6.0"
